name: "Test the action"
on:
  push:
    branches:
      - tester

jobs:
  test-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - run: npm ci --prod

      - run: "git config --global user.email 'changelog@github.com'"
      - run: "git config --global user.name 'Awesome Github action'"
      - run: "git add . && git commit --allow-empty -m 'feat: Added fake file so version will be bumped'"

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: "dont-use-git"
          EXPECTED_TAG: "v1.5.0"
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "pom.xml"
          version-path: "project.version"

      - name: Show file
        run: |
          echo "$(<pom.xml)"

      - name: Test output
        run: node ./test-output.js
        env:
          FILES: "pom.xml"
          EXPECTED_VERSION: "1.5.0"
          EXPECTED_VERSION_PATH: "project.version"
